builds:
- env:
  - CGO_ENABLED=0
  main: main.go
  binary: bin/{{ .ProjectName }}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
